wip

diff --git a/project-dev b/project-dev
--- a/project-dev
+++ b/project-dev
@@ -36,20 +36,20 @@ function buildJar() {
 function costumized_error_message () {
     local COLOR_RED="$(tput setaf 9 2>/dev/null || :)"
     local COLOR_RESET="$(tput sgr0 2>/dev/null || :)"
-    echo "${COLOR_RED}ERROR: "$1"${COLOR_RESET}" 1>&2;
+    echo "${COLOR_RED}ERROR: "$@"${COLOR_RESET}" 1>&2;
     exit 1
 }
 
 function costumized_success_message () {
     local COLOR_GREEN="$(tput setaf 10 2>/dev/null || :)"
     local COLOR_RESET="$(tput sgr0 2>/dev/null || :)"
-    echo "${COLOR_GREEN}INFO: "$1"${COLOR_RESET}" 1>&2;
+    echo "${COLOR_GREEN}INFO: "$@"${COLOR_RESET}" 1>&2;
 }
 
 function costumized_warning_message () {
     local COLOR_YELLOW="$(tput setaf 3 2>/dev/null || :)"
     local COLOR_RESET="$(tput sgr0 2>/dev/null || :)"
-    echo "${COLOR_YELLOW}WARNING: "$1"${COLOR_RESET}" 1>&2;
+    echo "${COLOR_YELLOW}WARNING: "$@"${COLOR_RESET}" 1>&2;
 }
 
 function codeRun() {
@@ -84,16 +84,17 @@ function performanceTesting() {
 function testCoverageReport() {
     checkMaven
     local REPORT_FILE=${ROOT_DIR}/target/site/jacoco/index.html
+    local REPORT_SUCCESS_MSG="The report visualized successfully. Generated file: ${REPORT_FILE}"
     cd ${ROOT_DIR}
     # run test coverage
     mvn clean test jacoco:report
-    # show report
+    # show reports
     if [ -x "$(command -v firefox -V)" ]; then
         firefox --new-window ${REPORT_FILE}
-        costumized_success_message "The report visualized successfully. Generated file: ${REPORT_FILE}"
+        costumized_success_message ${REPORT_SUCCESS_MSG}
     elif [ -x "$(command -v firefox -V)" ]; then
         google-chrome --new-window ${REPORT_FILE}
-        costumized_success_message "The report visualized successfully. Generated file: ${REPORT_FILE}"
+        costumized_success_message ${REPORT_SUCCESS_MSG}
     else
         costumized_warning_message "The report generated but couldn't visualize. Generated file: ${REPORT_FILE}"
     fi
