Added test coverage report to binary file (#37)

diff --git a/project-dev b/project-dev
--- a/project-dev
+++ b/project-dev
@@ -15,34 +15,41 @@ Usage: $0 <command>
         Runs containerized app
     performance-test
         Stress testing for the API
+    test-coverage-report
+        Shows unit test coverage reports
 "
 }
 
-function buildJar() {
+function checkMaven() {
+    # Check maven if installed or not. If not install
     if ! [ -x "$(command -v mvn --version)" ]; then
         echo "Installing maven"
         apt install maven
     fi
+}
+
+function buildJar() {
+    checkMaven
     mvn clean package -DskipTests && costumized_success_message "Jar file built succesfully" || costumized_error_message "Jar file could not build"
 }
 
 function costumized_error_message () {
     local COLOR_RED="$(tput setaf 9 2>/dev/null || :)"
     local COLOR_RESET="$(tput sgr0 2>/dev/null || :)"
-    echo "${COLOR_RED}ERROR: "$1"${COLOR_RESET}" 1>&2;
+    echo "${COLOR_RED}ERROR: "$@"${COLOR_RESET}" 1>&2;
     exit 1
 }
 
 function costumized_success_message () {
     local COLOR_GREEN="$(tput setaf 10 2>/dev/null || :)"
     local COLOR_RESET="$(tput sgr0 2>/dev/null || :)"
-    echo "${COLOR_GREEN}INFO: "$1"${COLOR_RESET}" 1>&2;
+    echo "${COLOR_GREEN}INFO: "$@"${COLOR_RESET}" 1>&2;
 }
 
 function costumized_warning_message () {
     local COLOR_YELLOW="$(tput setaf 3 2>/dev/null || :)"
     local COLOR_RESET="$(tput sgr0 2>/dev/null || :)"
-    echo "${COLOR_YELLOW}INFO: "$1"${COLOR_RESET}" 1>&2;
+    echo "${COLOR_YELLOW}WARNING: "$@"${COLOR_RESET}" 1>&2;
 }
 
 function codeRun() {
@@ -74,6 +81,26 @@ function performanceTesting() {
     locust -f ${ROOT_DIR}/performance-testing/locust.py --host ${HOST} --headless --users=${CONCURRENT} --spawn-rate=${RATE} --run-time=${DURATION}s --reset-stats --only-summary
 }
 
+function testCoverageReport() {
+    checkMaven
+    # mvn generates test coverage in this file by default
+    local REPORT_FILE=${ROOT_DIR}/target/site/jacoco/index.html
+    local REPORT_SUCCESS_MSG="The report visualized successfully. Generated file: ${REPORT_FILE}"
+    cd ${ROOT_DIR}
+    # run test coverage
+    mvn clean test jacoco:report
+    # show reports
+    if [ -x "$(command -v firefox -V)" ]; then
+        firefox --new-window ${REPORT_FILE}
+        costumized_success_message ${REPORT_SUCCESS_MSG}
+    elif [ -x "$(command -v firefox -V)" ]; then
+        google-chrome --new-window ${REPORT_FILE}
+        costumized_success_message ${REPORT_SUCCESS_MSG}
+    else
+        costumized_warning_message "The report generated but couldn't visualize. Generated file: ${REPORT_FILE}"
+    fi
+}
+
 function main() {
     case "${1-notset}" in
         help)
@@ -87,6 +114,9 @@ function main() {
             ;;
         performance-test)
             performanceTesting "${@}"
+            ;;
+        test-coverage-report)
+            testCoverageReport "${@}"
             ;;
         *)
             >&2 echo "Error: Unknown command: '${1-}'"
